** Français















*Description:*

- Permet de fusionner plusieurs morceaux de grille qui ont été découpées
  lors de la même exécution de SPOOKI.

  #+begin_quote
    */Notes:/*
    Ce plugin permet de créer une grille complètement autonome.
  #+end_quote

*Méthode d'itération:*

- Point par point.

*Dépendances:*

- Un ou plusieurs champ(s) sur plusieurs morceaux de grille.

*Résultat(s):*

- Champ(s) en entrée sur un grille reconstituée.

*Algorithme:*

- Les morceaux de grilles sont triés en fonction de leur grille
  d'origine. On vérifie ensuite qu'ils sont consécutifs et forment une
  grille rectangulaire dont on calcule les dimensions. On vérifie que
  chaque groupe de grilles est conforme et forme une grille de mêmes
  dimensions.
- Pour chaque groupe de morceaux de grille, une grille est créée en
  copiant les paramètres d'un morceau et en indiquant les dimensions
  précédemment calculées.
- On parcours ensuite, pour chaque groupe, chacun des morceaux afin de
  copier ses données à l'endroit correspondant dans la grille de sortie.
  Le positionnement des données est géré par un paramètre fixé lors du
  découpage de la grille.

*Références:*

- SYSTÈME/SYSTEM, grille/grid, fusion/merge

*Mots clés:*

- SYSTÈME/SYSTEM, grille/grid, fusion/merge

*Usage:*

*Exemple d'appel:* ==

#+begin_example
      ...
      spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/GridMerge/testsFiles/inputFile.std] >>
                  ([GridCut --startPoint 0,0 --endPoint 50,51] + [GridCut --startPoint 0,52 --endPoint 50,102]) >>
                  [GridMerge] >>
                  [WriterStd --output /tmp/$USER/outputFile.std]"
      ...
#+end_example

*Validation des résultats:*

*Contacts:*

- Auteur(e) : [[https://wiki.cmc.ec.gc.ca/wiki/User:Martinm][Maximilien
  Martin]]
- Codé par : [[https://wiki.cmc.ec.gc.ca/wiki/User:Martinm][Maximilien
  Martin]] [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortiers][Sébastien
  Fortier]]
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Voir la référence à [[file:GridMerge_8cpp.html][GridMerge]].

Tests unitaires



*Ce plugin utilise:*\\

*Ce plugin est utilisé par:*\\



  

