** Français















*Description:*

- Sélectionne un ou plusieurs champ(s) dans la structure interne de
  mémoire, selon un ou plusieurs argument(s) passé(s) dans les clés
  paramétrables.
- NOTE: dans le cas de champ(s) extrait(s) de fichiers standards, toute
  la méta-information est automatiquement sélectionnée avec toute
  sélection de champ(s) (sauf si une des clé(s) paramétrable(s)
  optionnelle(s) --noMetadata ou --metadataFieldName est spécifiée)

*Méthode d'itération:*

- Ne s'applique pas

*Dépendances:*

- Au moins un champ dans la structure interne de mémoire

*Résultat(s):*

- Un ou plusieurs champ(s) sélectionné(s) selon les arguments passé(s)
  dans les clés paramétrables

*Algorithme:*

#+begin_example
          Indexer, à l'aide d'une base de données, les enregistrements selon le ou les critère(s) de sélection
          Faire la sélection à l'aide du ou des index approprié(s)
          Retourner le résultat
#+end_example

*Références:*

- [[https://wiki.cmc.ec.gc.ca/wiki/Spooki/Documentation/Composantes_du_syst%C3%A8me#meteo_infos:][Composantes
  de la structure interne de mémoire]]
- [[https://wiki.cmc.ec.gc.ca/wiki/Spooki/Correspondance_Fichiers_STD_-_SPOOKI][Correspondance
  entre les descripteurs d'enregistrements de fichiers standards et les
  attributs de la mémoire interne de SPOOKI]]

*Mots clés:*

- SYSTÈME/SYSTEM, sélection/selection

*Usage:*

#+begin_quote
  */Notes:/*\\
  Les conditions suivantes doivent être réunies pour que la requête soit
  valide :

  - Lorsque plusieurs clés paramétrables sont spécifiées, la requête
    cherche strictement pour les champs répondant à *tous les critères
    de sélections* passés à travers les clés paramétrables (ex.
    --fieldName TT, TD --pdsLabel ETIKET --forecastHour 12 => pour que
    la requête soit un succès, il faut absolument avoir: au moins un
    champ appelé TT, à l'heure de prévision 12 et ayant pour étiquette
    ETIKET *ET* au moins un champ appelé TD, à l'heure de prévision 12
    et ayant pour étiquette ETIKET simultanément). Exception:
    --metadataFieldName ALL, dans ce cas, toute la méta-information est
    choisie peu importe les autres clés paramétrables.

  Actuellement, aucune distinction n'est possible, dans la sélection,
  entre les niveaux ETA et SIGMA, de même qu'entre les niveaux HYBRID et
  HYBRID_STAGGERED. Par conséquent, l'argument SIGMA de la clé
  paramétrable --verticalLevelType, retournera à la fois des niveaux
  SIGMA et ETA. De même, l'argument HYBRID retournera à la fois des
  niveaux HYBRID et HYBRID_STAGGERED.

  L'argument ARBITRARY_CODE de la clé paramétrable --verticalLevelType
  est utilisé pour désigner un type de niveau vertical qui ne correspond
  à aucun des types mentionnés dans la liste
#+end_quote

*Exemple d'appel:* ==

#+begin_example
      ...
      spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/Select/testsFiles/inputFile.std] >>
                  [Select    --fieldName UU] >>
                  [WriterStd --output /tmp/$USER/outputFile.std]"
      ...
#+end_example

*Validation des résultats:*

*Contacts:*

- Auteur(e) : [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortiers][Sébastien
  Fortier]]
- Codé par : [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortinf][François
  Fortin]], [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortiers][Sébastien
  Fortier]]
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Voir la référence à 


Tests unitaires



*Ce plugin utilise:*\\

*Ce plugin est utilisé par:*\\



  

