** Français















*Description:*

- Calcul de la température potentielle, température d'une parcelle d'air
  suivant une expansion ou compression adiabatique vers un niveau de
  pression de référence. Sur un tephigramme, ce procédé peut être
  visualisé en augmentant ou abaissant une parcelle selon une
  adiabatique sèche.\\
  \\
  */Note:/* La pression de référence utilisée ici est de 1000 hPa.

*Méthode d'itération:*

- Point par point

*Dépendances:*

- Température de l'air (TT)
- Pression (PX)\\
  \\
  */Note:/* : Assurez-vous de fournir à ce plugin les dépendances
  ci-haut mentionnées ou alors, les résultats des\\
  plugins appelés par celui-ci (Voir la section "Ce plugin utilise").
  Pour plus de détails sur cet usage\\
  alternatif, voir la page de
  [[https://wiki.cmc.ec.gc.ca/wiki/Spooki/Documentation/Description_g%C3%A9n%C3%A9rale_du_syst%C3%A8me#RefDependances][documentation.]]

*Résultat(s):*

- Température potentielle, TH (deg K)

*Algorithme:*

#+begin_example
      Pour TT, la température de l'air (deg K)
      et   PX, la pression de l'air (hPa)

      Calcul de TH, la température potentielle selon:

      TH = TT*(1000/PX)**(Rd/cpd)


      Où Rd est la constante du gaz pour l'air sec (Rd = 287.05 J/(kg*K)) et cpd est la chaleur spécifique de
      l'air sec (cpd = 1005.46 J/(kg*K)
#+end_example

*Références:*

- Markowski, P. and Y. Richardson, 2010: Mesoscale Meteorology in
  Midlatitudes. Wiley-Blackwell, 407 pp.
- Rogers, R. R. and M. K. Yau, 1989: A Short Course in Cloud Physics,
  3rd Ed. Butterworth Heinemann, 290 pp.

*Mots clés:*

- MÉTÉO/WEATHER, température/temperature, potentielle/potential

*Usage:*

*Exemple d'appel:* ==

#+begin_example
      ...
      spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/TemperaturePotential/testsFiles/inputFile.std] >>
                  [TemperaturePotential] >>
                  [WriterStd --output /tmp/$USER/outputFile.std]"
      ...
#+end_example

*Validation des résultats:*

*Contacts:*

- Auteur(e) : Neil Taylor
- Codé par : Jonathan Cameron,
  [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortinf][François Fortin]]
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Voir la référence à



Tests unitaires



*Ce plugin utilise:*\\

*Ce plugin est utilisé par:*\\



  

