** Français















*Description :*

- Calcul de la température potentielle du thermomètre mouillé en
  fonction de la température, le point de rosée ainsi que la température
  et pression du niveau de condensation par ascendance.

*Méthode d'itération :*

- Point par Point

*Dépendances :*

- Température de l'air (TT)\\
  \\
  *et* un des champs suivants:\\
  \\
- Humidité spécifique, HU
- Rapport de mélange de la vapeur d'eau, QV
- Température du point de rosée, TD
- Écart du point de rosée, ES
- Humidité relative, HR\\
  \\
  */Note:/* : Assurez-vous de fournir à ce plugin les dépendances
  ci-haut mentionnées ou alors, les résultats des\\
  plugins appelés par celui-ci (Voir la section "Ce plugin utilise").
  Pour plus de détails sur cet usage\\
  alternatif, voir la page de
  [[https://wiki.cmc.ec.gc.ca/wiki/Spooki/Documentation/Description_g%C3%A9n%C3%A9rale_du_syst%C3%A8me#RefDependances][documentation.]]

*Résultat(s) :*

- Température potentielle du thermomètre mouillé, TW (deg C)

*Algorithme :*

#+begin_example
      Appeler le plugin Pressure pour obtenir PX (hPa).
      Appeler le plugin TemperatureWetBulb pour obtenir TTW (deg C).

      Si PX < 5 hPa:

        TW = -999.0

      Sinon:

        Appeler le plugin TemperatureAlongPseudoAdiabat avec --endLevel 1000.0hPa et --direction BOTH puis retourner seulement les valeurs à
        1000 hPa pour obtenir TW (deg C).
#+end_example

*Références :*

- Bluestein, H. B., 1992: Synoptic-Dynamic Meteorology in Midlatitudes
  Volume 1: Principles of Kinematics and Dynamics. Oxford Univeristy
  Press, 431 pp.
- Rogers, R. R. and M. K. Yau, 1989: A Short Course in Cloud Physics,
  3rd Ed. Butterworth Heinemann, 290 pp.

*Mots clés :*

- MÉTÉO/WEATHER, température/temperature, potentielle/potential,
  thermomètremouillé/wet-bulb, humidité/humidity

*Usage:*

*Exemple d'appel:* ==

#+begin_example
      ...
      spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/TemperatureWetBulbPotential/testsFiles/inputFile.std] >>
                  [TemperatureWetBulbPotential] >>
                  [WriterStd --output /tmp/$USER/outputFile.std]"
      ...
#+end_example

*Validation des résultats:*

*Contacts:*

- Auteur(e) : Neil Taylor
- Codé par : Jonathan Cameron
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Voir la référence à



Tests unitaires



*Ce plugin utilise:*\\

*Ce plugin est utilisé par:*\\



  

