** Français















*Description:*

- Ecriture de données dans un fichier en format RPN standard
- Convertit par défaut, chaque variable dans l'unité correspondant au
  [[https://wiki.cmc.ec.gc.ca/wiki/Spooki/RelationsSpookiFSTD][dictionnaire
  de variables standards.]]

*Méthode d'itération:*

- Ne s'applique pas

*Dépendances:*

- Données dans la mémoire interne du système SPOOKI (PDS)

*Résultat(s):*

- Un ou des enregistrement(s) encodé(s) dans un fichier en format RPN
  standard
- Les enregistrements sont triés et écrits dans l'ordre suivant :
  meta-informations, ordre alphabétique de noms de variables, ordre de
  niveaux (de bas en haut), ordre temporel
- Les valeurs de IP2 et IP3 ne sont pas encodées et IP3 contient le
  delta de l'interval.

*Algorithme:*

- Avec l'aide du tableau sur la page de correspondance entre les
  [[https://wiki.cmc.ec.gc.ca/wiki/Spooki/Correspondance_Fichiers_STD_SPOOKI][fichiers
  standards et SPOOKI]], ce plugin transfère (écrit) l'information des
  attributs de la mémoire interne de SPOOKI aux descripteurs
  d'enregistrement des fichiers standards en suivant
  [[https://wiki.cmc.ec.gc.ca/wiki/Spooki/Tableau_r%C3%A8gles_pour_WriterStd][les
  règles suivantes]].
- Convertit chaque variable vers son unité standard tel que désignée par
  [[http://iweb.cmc.ec.gc.ca/~afsypst/spooki/spooki_french_doc/html/stdvar.html][le
  dictionnaire de variables standards]], à l'aide du plugin
  , sauf si la clé
  "--noUnitConversion" est activée. Lors de cette conversion, le
  deuxième caractère du TYPVAR n'est pas affecté. Si l'unité d'origine
  n'est pas connue, la conversion ne peut avoir lieu, le plugin arrête
  en indiquant: "L'unité n'est pas connue, si vous désirez écrire la
  variable avec l'unité d'origine, utilisez la clé
  &ndash;noUnitConversion."
- Trie les variables selon l'ordre désigné par le système
  (meta-informations, ordre alphabétique de noms de variables, ordre de
  niveaux (de bas en haut), ordre temporel).
- Si la clé "--noMetadata" est activée, ne copie pas les
  "meta-informations" (informations associées à la représentation
  spatiale: enregistrements ">>","^^","HY","P0","PT","E1","!!","!!SF").
- Si la clé "--metadataOnly" est activée, copie seulement les
  "meta-informations" (informations associées à la représentation
  spatiale: enregistrements ">>","^^","HY","P0","PT","E1","!!","!!SF").
- Ce plugin écrit au fichier nommé par l'argument donné à la clé
  "--output". Si ce fichier existe déjà, par défaut (option
  APPENDOVERWRITE de la clé "--writingMode"), on écrit par dessus les
  enregistrements qui ont les mêmes valeurs dans les descripteurs
  d'enregistrements que les nouvelles données et on garde les autres
  données déjà dans le fichier. Si on choisit l'option NOPREVIOUS de la
  clé "--writingMode" et que le fichier existe déjà, le plugin arrête
  avec un message approprié. Si on choisit l'option NEWFILEONLY, on
  efface le fichier et on crée un nouveau fichier contenant
  exclusivement les nouvelles données.
- Important: Si le fichier (dans l'argument de --output) existe déjà et
  que ce fichier n'est pas un fichier standard, la requête arrête
  indiquant que le fichier dans l'argument de --output existe déjà et
  n'est pas de type standard. On invite ensuite l'usager à résoudre le
  conflit avant de relancer SPOOKI.
- Le fichier final ne contient pas deux champs distincts de "HY" ou de
  "!!". Pour les "^^" et ">>", des champs distincts sont permis sauf
  s'ils ont les mêmes IP1 et IP2 mais pas les mêmes IG1,IG2,IG3 et IG4.
  Si un deuxième "HY" ou "!!" distincts ou des champs "^^" et ">>"
  distincts non-permis existent dans les données à écrire et/ou le
  fichier d'écriture, la requête arrête avec un message claire
  expliquant le problème.

*Références:*

- [[https://wiki.cmc.ec.gc.ca/images/8/8c/Spooki_-_An_Introduction_to_RPN_Standard_files.pdf][Documentation
  sur les fichiers standards]]
- [[https://wiki.cmc.ec.gc.ca/wiki/Spooki/Correspondance_Fichiers_STD_SPOOKI][Tableau
  de comparaison entre les fichiers standards et SPOOKI]]

*Mots clés:*

- IO, standard, graveur/writer, fichier/file

*Usage:*

#+begin_quote
  */Notes: Pour la clé "--writingMode":/*\\

  - NOPREVIOUS: Le plugin arrête si le fichier standard existe déjà.
  - APPEND : Si le fichier standard existe déjà , on rajoute tous les
    enregistrements dans la mémoire disponible aux plugin.
  - APPENDOVERWRITE: Si le fichier standard existe déjà, on écrit par
    dessus les enregistrements qui ont les mêmes valeurs dans les
    descripteurs d'enregistrement que les nouvelles données et on garde
    les autres données déjà dans le fichier. (Mode par défaut)
  - NEWFILEONLY: Si le fichier standard existe déjà, on efface le
    fichier et on crée un nouveau fichier contenant exclusivement les
    nouvelles données.

  *Exemple d'appel:* ==

  #+begin_example
        ...
            spooki_run "[ReaderStd --input  $SPOOKI_DIR/pluginsRelatedStuff/ReaderStd_WriterStd/testsFiles/inputFile.std] >>
                        [WriterStd --output /tmp/$USER/outputFile.std]"
        ...
  #+end_example

  *Validation des résultats:*

  *Responsables:*

  - Auteur(e) : [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortinf][François
    Fortin]] [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortiers][Sébastien
    Fortier]] [[https://wiki.cmc.ec.gc.ca/wiki/User:Pelletierl][Luc
    Pelletier]]
  - Codé par : [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortinf][François
    Fortin]] [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortiers][Sébastien
    Fortier]] [[https://wiki.cmc.ec.gc.ca/wiki/User:Pelletierl][Luc
    Pelletier]]
  - Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]]
    [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

  Voir la référence à [[file:WriterStd_8cpp.html][WriterStd]].

  Tests unitaires

  

  *Ce plugin utilise:*\\

  *Ce plugin est utilisé par:*\\

  

    
  
#+end_quote
