** Français















*Description:*

- Écriture de bulletins FBCN, en format ASCII, regroupant des prévisions
  de vent et de température en altitude, interpolées sur un ensemble de
  stations canadiennes aux hauteurs 3000, 6000, 9000, 12000 et 18000
  pieds. Les bulletins sont produits à 06h (FBCN31), 12h (FBCN33) et 24h
  (FBCN35) de prévision.
- Des bulletins de remplacement (backups) sont produits en cas de
  problèmes avec les deux passes régionales subséquentes (passe courante
  +6 heures et passe courante + 12 heures).

*Méthode d'itération:*

- Ne s'applique pas

*Dépendances:*

- Module du vent (UV) calculé aux stations et aux hauteurs 3000, 6000,
  9000, 12000 et 18000 pieds à une des heures de prévision: 6, 12, 18,
  24, 30 et 36.
- Direction du vent météorologique (WD) calculée aux stations et aux
  hauteurs 3000, 6000, 9000, 12000 et 18000 pieds à une des heures de
  prévision: 6, 12, 18, 24, 30 et 36.
- Température de l'air (TT) interpolée aux stations et aux hauteurs
  3000, 6000, 9000, 12000 et 18000 pieds à une des heures de prévision:
  6, 12, 18, 24, 30 et 36.
- Altitude géopotentielle (GZ) à la surface, interpolée aux stations.
- Élévation terrestre (TerrainElevation) de chacune des stations.
- Latitude (LAT) de chacune des stations.
- Longitude (LON) de chacune des stations.
- Code d'identification (StationAlphaID) de chacune des stations (code
  de 4 lettres maximum).

NOTE: Ces dépendances peuvent être au préalable obtenues par le plugin
.

*Résultat(s):*

- Un bulletin FBCN CWAO à 06h, 12h ou 24h de prévision, nommé
  FBCN{31-33-35}.
- Selon l'heure de prévision, un ou deux bulletin(s) utilisé(s) comme
  bulletin(s) de remplacement, en cas de problèmes avec la ou les deux
  prochaines passes régionales opérationnelles (backup 6 et backup 12),
  nommé(s) FBCN{31-33-35}_backup{06-12}.
- À l'intérieur des bulletins (réguliers et de remplacement) , les
  stations sont ordonnées selon l'ordre suivant : les stations au sud de
  60N ordonnées d'ouest en est et du nord au sud, puis les stations au
  nord de 60N ordonnées d'ouest en est et du nord au sud.

*Algorithme:*

#+begin_example
  1. Construction des en-têtes pour chaque bulletin en fonction de l'heure de la passe et de l'heure de
     prévision (6, 12, 18, 24, 30 et 36) sous le format ASCII pré-défini à 6, 12 ou 24h.

     Le plugin détermine les composantes temporelles à indiquer dans l'en-tête du bulletin, soit :

        - temps approximatif de sortie du bulletin :
             - heure de la passe + 3h20 , si l'heure de prévision = 6h
             - heure de la passe + 3h30 , si l'heure de prévision = 12h ou 24h

        - heure de validité = heure de la passe + heure de prévision

        - période d'utilisation :
             - (heure de validité - 4h) à (heure de validité + 3h) , si l'heure de prévision = 6h
             - (heure de validité - 3h) à (heure de validité + 6h) , si l'heure de prévision = 12h
             - (heure de validité - 6h) à (heure de validité + 6h) , si l'heure de prévision = 24h

  2. Ecriture des en-têtes des bulletins concernés.

  3. Tri des stations : les stations au sud de 60N (inclusivement) sont ordonnées d'ouest en est, du nord au sud puis
     les stations au nord de 60N, d'ouest en est, du nord au sud.

  4. Préparation des données pour chaque station et pour chaque hauteur (3000, 6000, 9000, 12000 et 18000 pieds) :

        - Aucune prévision est écrite à la hauteur 3000 pieds si:
             - l'altitude de la station est supérieure à 1500 pieds
          ou
             - la hauteur géopotentielle à la station (converties en pieds) est supérieure ou égale à 3000 pieds

        - Combinaison de UV, WD et TT dans un format DDFFTT, où DD est la direction du vent en dizaines de degrés,
          FF la vitesse du vent en noeuds et TT la température de l'air en deg C, arrondie en entier le plus proche
          et signée (ex: TT = -16.85 deg C -> TT = -17)
          Les valeurs DD et FF sont calculées de la façon suivante :
             - la direction du vent WD est convertie en dizaines de degrés, puis arrondie en entier le plus proche pour
               obtenir DD (ex: WD = 247 deg -> 24.7 -> DD = 25)
             - si 100 <= UV <= 199 kts, alors :
                  - le module du vent UV est arrondi en entier le plus proche pour obtenir FF et :
                        DD = DD + 50
                        FF = FF - 100
             - si UV >  199, alors :
                        FF = 99
             - si UV < 5, alors :
                        DD = 99
                        FF = 00

        - Si TT (température arrondie en entier) est de 999 deg C, cela indique une valeur non disponible à cette hauteur,
          on assigne alors les valeurs suivantes:
                        TT=99
                        DD=99
                        FF=99
          On affiche ces valeurs uniquement pour les niveaux supérieurs à 3000 pieds. La condition mentionnée précédemment
          sur l'écriture des prévisions à 3000 pieds s'applique toujours.

        - Les températures ne sont pas prévues pour la hauteur 3000 pieds (ie, DDFFTT devient DDFF seulement)

        - Troncation du code d'identification de chaque station pour ne conserver que les trois dernières lettres
          (ex: CYUL devient YUL)

        - En fonction des heures de prévision, production d'un bulletin "backup" aux heures indiquées par la clé "backupHour",
          avec ajout de la ligne appropriée dans l'en-tête du bulletin.

        - Messages d'avertissements envoyés si :
            - l'heure de prévision ne correspond à aucune sortie planifiée de bulletin régulier.
            - le(s) bulletins(s) de remplacement demandé(s) correspond(ent) à aucun bulletin planifié de ce type.

        - Transfert des bulletins et des bulletins de remplacement, si disponibles à l'adresse indiquée par la clé "outputPath"

  Note :  Une journée est ajoutée à la date de validité dans l'en-tête du bulletin si l'heure de validité dépasse 24h
#+end_example

*Références:*

- Pour de l'information détaillée sur les bulletins FDCN, consulter le
  [[http://www.msc-smc.ec.gc.ca/msb/manuals/manair/pdf/french/chap3_f.pdf][Chapitre
  3]] du
  [[http://www.msc-smc.ec.gc.ca/msb/manuals/manair/html/PDFMenu_f.cfm][MANAIR]]\\
- Concernant la conversion des bulletins FDCN au format FBCN, consulter
  [[https://wiki.cmc.ec.gc.ca/images/2/23/Spooki_-_Conversion_FD-FB.doc][ce]]
  document

*Mots clés:*

- IO, aviation, bulletin, vent/wind, température/temperature, FBCN,
  ASCII, station, backup, verticale/vertical

*Usage:*

*Exemple d'appel:* ==

#+begin_example
          ...
              spooki_run "[ReaderStd --input  $SPOOKI_DIR/pluginsRelatedStuff/WriterAsciiBulletinFB/testsFiles/inputFile.std] >>
                          [Select --verticalLevel 0.384@1.0] >>
                          [BulletinFBPreparation] >>
                          [WriterAsciiBulletinFB --outputPath /tmp/$USER]"
#+end_example

==

#+begin_example
          ...
      
#+end_example

*Validation des résultats:*

*Responsables:*

- Auteur(e) : [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortiers][Sébastien
  Fortier]]
- Codé par : [[https://wiki.cmc.ec.gc.ca/wiki/User:Pelletierl][Luc
  Pelletier]] [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortiers][Sébastien
  Fortier]]
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]]
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Voir la référence à
[[file:WriterAsciiBulletinFB_8cpp.html][WriterAsciiBulletinFB]].

Tests unitaires



*Ce plugin utilise:*\\

*Ce plugin est utilisé par:*\\



  

