** Français

*** Description:
    Calcul du module du vent à partir de ses 2 composantes horizontales.

*** Méthode d'itération:
    Point par point

*** Dépendances:
    Composante UU du vent (selon l'axe des X sur la grille). Composante
    VV du vent (selon l'axe des Y sur la grille).

*** Résultat(s):
    Module du vent, UV, dans les mêmes unités que ses dépendances.

*** Algorithme:
    #+BEGIN_QUOTE
        UV = (UU**2 + VV**2)**.5
    #+END_QUOTE

*** Références:
    Ne s'applique pas

*** Mots clés:
    MÉTÉO/WEATHER, module/modulus, vent/wind, vitesse/speed

*** Usage:

**** Exemple d'appel:
    #+BEGIN_SRC python
        python3
        import fstpy.all as fstpy
        import spookipy.all as spooki
        records=fstpy.StandardFileReader(SPOOKI_DIR + "/pluginsRelatedStuff/WindModulusAndDirection/testsFiles/inputFile.std").to_pandas()
        s=spooki.WindModulus(records).compute()
        fstpy.StandardFileWriter("/tmp/"+USER+"/outputFile.std",records).to_fst()
    #+END_SRC

*** Validation des résultats:

*** Contacts:
    Auteur(e) : 
        [[https://wiki.cmc.ec.gc.ca/wiki/User:Beaucheminm][Maryse Beauchemin]] 

    Codé par : 
        [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortinf][François Fortin]]    

    Support :
        - [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]]
        - [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

** English

*** Description:
    Calculation of the wind modulus from its 2 horizontal components.

*** Iteration method:
    Point-by-point

*** Dependencies:
    UU component of the wind (along the X axis of the grid). VV
    component of the wind (along the Y axis of the grid).

*** Result(s):
    Wind modulus, UV, in the same units as the dependencies.

*** Algorithm:
    #+BEGIN_QUOTE
        UV = (UU**2 + VV**2)**.5
    #+END_QUOTE

*** Reference:
    Does not apply

*** Keywords:
    MÉTÉO/WEATHER, module/modulus, vent/wind, vitesse/speed

*** Usage:

**** Call example:
    #+BEGIN_SRC python
        python3
        import fstpy.all as fstpy
        import spookipy.all as spooki
        records=fstpy.StandardFileReader(SPOOKI_DIR + "/pluginsRelatedStuff/WindModulusAndDirection/testsFiles/inputFile.std").to_pandas()
        s=spooki.WindModulus(records).compute()
        fstpy.StandardFileWriter("/tmp/"+USER+"/outputFile.std",records).to_fst()
    #+END_SRC

*** Contacts:

    Author :
        [[https://wiki.cmc.ec.gc.ca/wiki/User:Beaucheminm][Maryse Beauchemin]] 
    
    Coded by :
        [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortinf][François Fortin]]

    Support :
        - [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]]
        - [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

