** Français

*Description:*

- Calcul de la pression de vapeur d'eau.\\
  \\
  */Note:/* Si calculé à partir de HR ou ES/TD, l'utilisateur devra
  définir si ceux-ci ont été calculés par rapport à la glace ou à l'eau
  liquide.

*Méthode d'itération:*

- Point par point

*Dépendances:*

- Humidité spécifique, HU\\
  ou\\
- Le rapport de mélange de la vapeur d'eau, QV\\
  ou\\
- Température de l'air, TT\\
  *et* un des champs suivants:
- Humidité relative, HR
- La température du point de rosée, TD / L'écart du point de rosée, ES

*Résultat(s):*

- Pression de vapeur, VPPR (hPa)

*Algorithme:*

#+begin_example
        -Si la clé --RPN n'est pas activée:

            *Si le champ d'entrée est l'humidité spécifique, HU (kg/kg):
                Calculer la pression atmosphérique, PX (hPa) avec le plugin Pressure.
                   VPPR= (HU*PX) / ( epsilon + HU*(1-epsilon) )
                où la pression de vapeur, VPPR est en hPa et epsilon est défini dans la table des constantes comme 0.6219800221014e+00 et correspond à Rd/Rv.


            *Si le champ d'entrée est le rapport de mélange de la vapeur d'eau, QV (kg/kg):
                Calculer la pression atmosphérique, PX (hPa) avec le plugin Pressure.
                   VPPR= (QV*PX) / (epsilon + QV)
                où la pression de vapeur, VPPR est en hPa et epsilon est défini dans la table des constantes comme 0.6219800221014e+00 et correspond à Rd/Rv.


            *Si les champs d'entrées sont l'humidité relative, HR (fraction) et la température de l'air, TT (deg C):
                Calculer la pression de vapeur saturante, SVP (hPa) en utilisant le plugin SaturationVapourPressure.
                   VPPR = HR*SVP
                où la pression de vapeur, VPPR est en hPa.


            *Si les champs d'entrée sont l'écart du point de rosée, ES (deg C)/ température du point de rosée, TD (deg C) et la température de l'air, TT (deg C):
                Soit TPL, la température à laquelle il faut changer de saturation par rapport à l'eau à la saturation par rapport à la glace (deg C)
                Calculer la température du point de rosée, TD (deg C) avec le plugin TemperatureDewPoint si nécessaire.

                Si TT>TPL ou --iceWaterPhase WATER
                   VPPR = AEw1 * exp( (AEw2*TD)/(AEw3 +TD)
                Sinon
                   VPPR = AEi1 * exp( (AEi2*TD)/(AEi3 +TD)

                où la pression de vapeur, VPPR est en hPa et où selon Alduchov et Eskridge (1996)
                AEw1=6.1094   AEi1=6.1121
                AEw2=17.625   AEi2=22.587
                AEw3=243.04   AEi3=273.86


        -Si la clé --RPN est activée:

            *Si le champ d'entrée est l'humidité spécifique, HU (kg/kg):
                Calculer la pression, PX (Pa) avec le plugin Pressure.
                Appeler la fonction rpn sfoefq.ftn90 pour obtenir la pression de vapeur, VPPR (Pa).

            *Si le champ d'entrée est le rapport de mélange de la vapeur d'eau, QV (kg/kg):
                Il n'existe pas de fonction RPN pour ce calcul, nous utilisons donc:
                Calculer la pression, PX (hPa) avec le plugin Pressure.
                   VPPR= (QV*PX) / (epsilon + QV)
                où la pression de vapeur, VPPR est en hPa et epsilon est défini dans la table des constantes comme 0.6219800221014e+00 et correspond à Rd/Rv.

            *Si les champs d'entrée sont l'humidité relative HR (fraction) et la température de l'air, TT (deg K):
                Calculer l'humidité spécifique, HU (kg/kg) avec le plugin HumiditySpecific  (avec les mêmes clés et leurs arguments).
                Calculer la pression, PX (Pa) avec le plugin Pressure.
                Appeler la  la fonction rpn sfoefq.ftn90 pour obtenir la pression de vapeur, VPPR (Pa).

            *Si les champs d'entrée sont l'écart du point de rosée, ES (deg K ou deg C)/température du point de rosée, TD(deg K) et la température de l'air, TT (deg K):
                Soit TPL, la température à laquelle il faut changer de la saturation par rapport à l'eau à la saturation par rapport à la glace (deg K)
                Calculer la température du point de rosée, TD (deg K) avec le plugin TemperatureDewPoint.

                Si TT > TPL ou --iceWaterPhase WATER
                   Appeler la fonction sfoewa.ftn avec TD pour obtenir la pression de vapeur, VPPR (Pa).
                Sinon
                   Appeler la fonction sfoew.ftn avec TD pour obtenir la pression de vapeur, VPPR (Pa).


            Convertir la pression de vapeur, VPPR en hPa si VPPR est en Pa.
               VPPR(hPa)= VPPR(Pa) / 100.0

    Notes:  Lorsque plusieurs champs des dépendances et le champ TT sont disponibles en entrée, le calcul sera effectué avec le champ qui a le plus de niveaux en commun avec TT dans l'ordre de préférence (en cas d'égalité) HU suivi de QV, HR et finalement ES/TD.
            Lorsque le champ TT n'est pas disponible, le calcul sera effectué de préférence avec HU suivi de QV sans tenir compte du nombre de niveaux disponibles.
#+end_example

*Références:*

- Rogers, R. R. and M. K. Yau, 1989: A Short Course in Cloud Physics,
  3rd Ed. Butterworth Heinemann, 290 pp.
- [[http://journals.ametsoc.org/doi/pdf/10.1175/1520-0450%281996%29035%3C0601%3AIMFAOS%3E2.0.CO%3B2][Alduchov,
  O. A., and R. E. Eskridge, 1996: Improved Magnus form approximation of
  saturation vapor pressure. ''J. Appl. Meteor.'', '''35''', 601-609]]
- [[https://wiki.cmc.ec.gc.ca/wiki/RPT/Analyse_de_la_pression_de_vapeur][Analyse
  de la pression de vapeur]]
- [[https://wiki.cmc.ec.gc.ca/images/6/60/Tdpack2011.pdf][Librairie
  thermodynamique de RPN]]

*Mots clés:*

- MÉTÉO/WEATHER, humidité/humidity, pression/pressure

*Usage:*

*Exemple d'appel:* 

#+begin_example
      ...
      spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/VapourPressure/testsFiles/inputFile.std] >>
                  [VapourPressure] >>
                  [WriterStd --output /tmp/$USER/outputFile.std]"
      ...
#+end_example

*Validation des résultats:*

*Contacts:*

- Auteur(e) : Neil Taylor
- Codé par : Jonathan Cameron,
  [[https://wiki.cmc.ec.gc.ca/wiki/User:Hardyg][Guylaine Hardy]]
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Voir la référence à 


Tests unitaires



*Ce plugin utilise:*\\

*Ce plugin est utilisé par:*\\



  

** English

*Description:*

- Calculates the vapour pressure of water.\\
  \\
  */Note:/* If calculating from HR or ES/TD the user has to define if
  these were calculated with respect to water saturation or ice
  saturation

*Iteration method:*

- Point-by-point

*Dependencies:*

- Specific Humidity, HU\\
  or\\
- Water vapour mixing ratio, QV\\
  or\\
- Air Temperature, TT\\
  *and* one of the following fields:
- Relative Humidity, HR
- Dew point temperature, TD / Dew point depression, ES

*Result(s):*

- Vapour pressure, VPPR (hPa)

*Algorithm:*

#+begin_example
      -If the --RPN key is NOT activated:

          *If the input field is the specific humidity, HU (kg/kg):
              Calculate the atmospheric pressure, PX (hPa) with the Pressure plug-in.
              VPPR= (HU*PX) / ( epsilon + HU*(1-epsilon) )
              where the vapour pressure, VPPR is in hPa and epsilon is defined in the table of constants as 0.6219800221014e+00 and corresponds to Rd/Rv.


          *If the input field is the water vapour mixing ratio, QV (kg/kg)
              Calculate the atmospheric pressure, PX (hPa) with the Pressure plug-in.
              VPPR= (QV*PX) / (epsilon + QV)
              where the vapour pressure, VPPR is in hPa and epsilon is defined in the table of constants as 0.6219800221014e+00 and corresponds to Rd/Rv.


          *If the input fields are the relative humidity, HR (fraction) and the air temperature, TT (deg C)
              Calculate the saturation vapour pressure, SVP (hPa) by using the SaturationVapourPressure plug-in.
              VPPR = HR*SVP
              where the vapour pressure, VPPR is in hPa.


          *If the input fields are the dew point depression, ES (deg C or deg K)/ dew point temperature, TD (deg C) and the air temperature, TT (deg C)
              For TPL, the temperature at which we must change from the saturation with respect to water to the saturation with respect to ice (deg C)
              Calculate the dew point temperature, TD (deg C), with the TemperatureDewPoint plug-in.

              If TT>TPL or --iceWaterPhase WATER
                  VPPR = AEw1 * exp( (AEw2*TD)/(AEw3 + TD) )
              else
                  VPPR = AEi1 * exp( (AEi2*TD)/(AEi3 + TD) )

              where the vapour pressure, VPPR is in hPa and where according to Alduchov and Eskridge (1996)
              AEw1=6.1094   AEi1=6.1121
              AEw2=17.625   AEi2=22.587
              AEw3=243.04   AEi3=273.86


      -If the --RPN key is activated:

          *If the input field is the specific humidity, HU (kg/kg)
              Calculate the pressure, PX (Pa) with the Pressure plug-in
              Call the rpn function sfoefq.ftn90 to obtain the vapour pressure, VPPR (Pa)

          *If the input field is the water vapour mixing ratio, QV (kg/kg)
              Calculate the pressure, PX (hPa) with the Pressure plug-in.
              There is no RPN function for this calculation, we therefore use:
              VPPR= (QV*PX) / (epsilon + QV)
              where the vapour pressure, VPPR is in hPa and epsilon is defined in the table of constants as 0.6219800221014e+00 and corresponds to Rd/Rv.

          *If the input fields are the relative humidity HR (fraction) and the air temperature, TT (deg K)
              Calculate the specific humidity, HU (kg/kg) with the HumiditySpecific plug-in (with the same keys and their arguments)
              Calculate the pressure, PX (hPa) with the Pressure plug-in.
              Call the rpn function sfoefq.ftn90 to obtain the vapour pressure, VPPR (Pa)

          *If the input fields are the dew point depression, ES (deg K or deg C)/ dew point temperature, TD (deg K) and the air temperature (deg K)
              For TPL, the temperature at which we must change from the saturation with respect to water to the saturation with respect to ice (deg K)
              Calculate the dew point temperature, TD (deg K), with the TemperatureDewPoint plug-in.

              If TT >TPL or --iceWaterPhase Water
                  Call the rpn function sfoewa.ftn90 with TD to obtain the vapour pressure, VPPR (Pa)
              else
                  Call the rpn fucntion sfoew.ftn90 with TD to obtain the vapour pressure, VPPR (Pa)


      Convert the vapour pressure, VPPR to hPa if VPPR is in Pa
          VPPR(hPa)= VPPR(Pa) / 100.0


  Notes: When several fields of the dependencies and TT are available in the input, the calculation will be done with the field that has the most number of levels in common with TT, in order of preference (in case of equality) with HU followed by QV, HR and finally ES/TD.
         When the TT field is not available, the calculation will be done in order of preference with HU followed by QV disregarding the number of levels.
#+end_example

*Reference:*

- Rogers, R. R. and M. K. Yau, 1989: A Short Course in Cloud Physics,
  3rd Ed. Butterworth Heinemann, 290 pp.
- [[http://journals.ametsoc.org/doi/pdf/10.1175/1520-0450%281996%29035%3C0601%3AIMFAOS%3E2.0.CO%3B2][Alduchov,
  O. A., and R. E. Eskridge, 1996: Improved Magnus form approximation of
  saturation vapor pressure. ''J. Appl. Meteor.'', '''35''', 601-609]]
- [[https://wiki.cmc.ec.gc.ca/wiki/RPT/Analyse_de_la_pression_de_vapeur][Analyse
  de la pression de vapeur]]
- [[https://wiki.cmc.ec.gc.ca/images/6/60/Tdpack2011.pdf][RPN
  thermodynamic library]]

*Keywords:*

- MÉTÉO/WEATHER, humidité/humidity, pression/pressure

*Usage:*

*Call example:* 

#+begin_example
      ...
      spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/VapourPressure/testsFiles/inputFile.std] >>
                  [VapourPressure] >>
                  [WriterStd --output /tmp/$USER/outputFile.std]"
      ...
#+end_example

*Results validation:*

*Contacts:*

- Author : Neil Taylor
- Coded by : Jonathan Cameron
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Reference to 


Units tests

*Uses:*\\

*Used by:*\\



  

