variables:
  ORD_SOUMET_CPUS: "20"
  ORD_SOUMET_CM: "20G"
  ORD_SOUMET_TMPFS: "10G"
  JOB_CPUS: "10"
  JOB_WALLCLOCK: "3600"
  doc_install_dir: "/home/spst900/public_html/spookipy/${CI_BUILD_REF_NAME}"
  latest_doc_install_dir: "/home/spst900/public_html/spookipy/latest"
  temp_dir: "/home/sgci800/cache/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}"

stages:
  - run_regtests
  - make_doc
  - install_doc
  - ssm_package


before_script:
  - export ORDENV_SITE_PROFILE=20220214
  - export ORDENV_COMM_PROFILE=eccc/20220217
  - export ORDENV_GROUP_PROFILE=eccc/cmc/1.9.7
  - . /fs/ssm/main/env/ordenv-boot-20201118.sh
  - export EC_ATOMIC_PROFILE_VERSION=1.15.0
  - . $ARMNLIB_SHARE/check_profile_1.1.0
  - . r.load.dot eccc/mrd/rpn/MIG/ENV/migdep/5.1.1 eccc/mrd/rpn/MIG/ENV/rpnpy/2.1.2
  - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmde/surge/surgepy/1.0.8/
  - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmds/apps/ci_fstcomp/1.0.8
  - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmds/fstpy/2.1.14/
  


run_regtests:
  stage: run_regtests
  script:
    - cd test
    - python3 -m pytest -v -m regressions

make_doc:
  stage: make_doc
  script:
    - cd doc
    - make doc
  artifacts:
    paths:
      - doc/_build/html


install_doc:
  stage: install_doc
  script:
    - cd doc/_build/html
    - cdir=`pwd`
    - rm -rf ${doc_install_dir}
    - mkdir -p ${doc_install_dir}
    - cp -r ${cdir}/* ${doc_install_dir}
    - echo "Installed in ${doc_install_dir}"
    - echo "Visit http://web.science.gc.ca/~spst900/spookipy/${CI_BUILD_REF_NAME}"

install_latest_doc:
  stage: install_doc
  only:
      - master
  script:
    - cd doc/_build/html
    - cdir=`pwd`
    - rm -rf ${latest_doc_install_dir}
    - mkdir -p ${latest_doc_install_dir}
    - cp -r ${cdir}/* ${latest_doc_install_dir}
    - echo "Installed in ${latest_doc_install_dir}"
    - echo "Visit http://web.science.gc.ca/~spst900/spookipy/latest"

ssm_package_with_everything:
  stage: ssm_package
  script:
    - cd livraison
    - export SSM_TEST_SPOOKIPY=1
    - ./make_ssm_package.py --install --temp ${temp_dir}/${CI_BUILD_STAGE}
    - . ssmuse-sh -x ${temp_dir}/${CI_BUILD_STAGE}/spookipy/$( cat ../VERSION )/all
    - ./test_ssm_package.py
    - mv spookipy_*.ssm ${temp_dir}
    - rm -r ${temp_dir}/${CI_BUILD_STAGE}

ssm_package_with_operation_yaml_list:
  stage: ssm_package
  script:
    - cd livraison
    - export SSM_TEST_SPOOKIPY=1
    - ./make_ssm_package.py --yaml plugin_list_operation.yaml --suffix operation --install --temp ${temp_dir}/${CI_BUILD_STAGE}
    - . ssmuse-sh -x ${temp_dir}/${CI_BUILD_STAGE}/spookipy/$( cat ../VERSION )/all
    - ./test_ssm_package.py --yaml plugin_list_operation.yaml
    - mv spookipy_*.ssm ${temp_dir}
    - rm -r ${temp_dir}/${CI_BUILD_STAGE}
