
variables:
  ORD_SOUMET_CPUS: "20"
  ORD_SOUMET_CM: "20G"
  ORD_SOUMET_TMPFS: "10G"
  JOB_CPUS: "10"
    

stages:
  - run_unittest
  - run_regtests
  - make_doc
  - install_doc
  - ssm_package


before_script:
  - export ORDENV_SITE_PROFILE=20200724
  - export ORDENV_COMM_PROFILE=eccc/20200724
  - export ORDENV_GROUP_PROFILE=eccc/cmc/1.9.3
  - . /fs/ssm/main/env/ordenv-boot-20201118.sh
  - export EC_ATOMIC_PROFILE_VERSION=1.12.0
  - . r.load.dot eccc/mrd/rpn/MIG/ENV/migdep/5.1.1 eccc/mrd/rpn/MIG/ENV/rpnpy/2.1.2
  - . ssmuse-sh -x cmd/cmdm/satellite/master_u1/miniconda3_4.9.2_ubuntu-18.04-skylake-64
  - . activate fstpy_full
  - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmds/fstpy/2.1.2/  


run_unittest: 
  stage: run_unittest 
  script:
    - cd test    
    # - python -m pytest -n 10 -m unit_tests 
    

run_regtests:
  stage: run_regtests
  script:
    - cd test
    - python -m pytest -m regressions

make_doc:
  stage: make_doc
  script:
    - cd doc
    - make doc
  artifacts:
    paths:
      - doc/_build/html 

      
install_doc:
  stage: install_doc
  script:
    - cd doc/_build/html
    - cdir=`pwd`
    - ssh sbf000@ppp3 'rm -rf /home/sbf000/public_html/spookipy/latest/*'
    - ssh sbf000@ppp3 cp -r ${cdir}/* /home/sbf000/public_html/spookipy/latest/

ssm_package:
  stage: ssm_package
  script:
    - cd ssm
    - ./make_package.sh






