variables:
  ORD_SOUMET_CPUS: "20"
  ORD_SOUMET_CM: "20G"
  ORD_SOUMET_TMPFS: "10G"
  ORD_SOUMET_T: "3600"
  doc_install_dir: "/home/spst900/public_html/spookipy/${CI_BUILD_REF_NAME}"
  latest_doc_install_dir: "/home/spst900/public_html/spookipy/latest"
  temp_dir: "/home/sgci800/cache/${CI_PROJECT_PATH}/${CI_BUILD_REF_NAME}/${CI_PIPELINE_ID}"
  deploy_dir_prefix: /fs/site5/eccc/cmd/w/spst900/spooki/CI_spookipy/${CI_BUILD_REF_NAME}
  ssm_dir_prefix: /space/hall5/sitestore/eccc/cmd/s/sgci800/ci_ssm_dir/spookipy

stages:
  - run_regtests
  - make_doc
  - install_doc
  - ssm_package
  - deploy
  - keep_ssm_package


before_script:
  - export ORDENV_SITE_PROFILE=20230929
  - export ORDENV_COMM_PROFILE=eccc/20231121
  - export ORDENV_GROUP_PROFILE=eccc/cmc/1.16.0
  - . /fs/ssm/main/env/ordenv-boot-20231110.sh
  - export EC_ATOMIC_PROFILE_VERSION=1.34.0
  - . $ARMNLIB_SHARE/check_profile_1.1.0
  - . r.load.dot eccc/mrd/rpn/MIG/ENV/rpnpy/2.2.0 eccc/mrd/rpn/code-tools/ENV/cdt-1.6.6/SCIENCE/inteloneapi-2022.1.2
  - . r.load.dot eccc/mrd/rpn/libs/20230906 eccc/cmd/cmda/libs/20230906/inteloneapi-2022.1.2
  - . ssmuse-sh -p /fs/ssm/eccc/cmd/cmds/env/python/py310_2023.07.28_all
  - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmds/apps/ci_fstcomp/1.0.9
  - . ssmuse-sh -x /fs/site5/eccc/cmd/w/spst900/spooki/CI_fstpy/master/latest/fstpy/*/all
  - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmds/cmcdict/202407/00

run_regtests:
  stage: run_regtests
  script:
    - cd test
    - python3 -m pytest -v -m regressions

make_doc:
  stage: make_doc
  script:
    - cd doc
    - make doc
  artifacts:
    paths:
      - doc/_build/html


install_doc:
  stage: install_doc
  script:
    - cd doc/_build/html
    - cdir=`pwd`
    - rm -rf ${doc_install_dir}
    - mkdir -p ${doc_install_dir}
    - cp -r ${cdir}/* ${doc_install_dir}
    - echo "Installed in ${doc_install_dir}"
    - echo "Visit http://web.science.gc.ca/~spst900/spookipy/${CI_BUILD_REF_NAME}"

install_latest_doc:
  stage: install_doc
  only:
      - master
  script:
    - cd doc/_build/html
    - cdir=`pwd`
    - rm -rf ${latest_doc_install_dir}
    - mkdir -p ${latest_doc_install_dir}
    - cp -r ${cdir}/* ${latest_doc_install_dir}
    - echo "Installed in ${latest_doc_install_dir}"
    - echo "Visit http://web.science.gc.ca/~spst900/spookipy/latest"

ssm_package_with_everything:
  stage: ssm_package
  script:
    - cd livraison
    - export SSM_TEST_SPOOKIPY=1
    - DEPLOY_DIR=${deploy_dir_prefix}/${CI_PIPELINE_ID}
    - echo ${DEPLOY_DIR}
    - ./make_ssm_package.py --install --temp ${DEPLOY_DIR}
    - echo $(pwd -P)
    - . ssmuse-sh -x ${DEPLOY_DIR}/spookipy/$( grep __version__ ../spookipy/__init__.py | awk '{print $3}' | tr -d "'" )/all
    - ./test_ssm_package.py
    - cp spookipy_*.ssm ${temp_dir}
  artifacts:
    expire_in: 1 hrs
    paths:
      - livraison/

ssm_package_with_operation_yaml_list:
  stage: ssm_package
  script:
    - cd livraison
    - export SSM_TEST_SPOOKIPY=1
    - UNIQUE_TEMP_DIR=${temp_dir}/${CI_JOB_ID}
    - echo ${UNIQUE_TEMP_DIR}
    - ./make_ssm_package.py --yaml plugin_list_operation.yaml --suffix operation --install --temp ${UNIQUE_TEMP_DIR}
    - echo $(pwd -P)
    - . ssmuse-sh -x ${UNIQUE_TEMP_DIR}/spookipy/$( grep __version__ ../spookipy/__init__.py | awk '{print $3}' | tr -d "'" )/all
    - ./test_ssm_package.py --yaml plugin_list_operation.yaml
    - cp spookipy_*.ssm ${temp_dir}
    - rm -r ${UNIQUE_TEMP_DIR}
  artifacts:
    expire_in: 1 hrs
    paths:
      - livraison/

ssm_package_with_official_fstpy:
  stage: ssm_package
  before_script:
    - export ORDENV_SITE_PROFILE=20230929
    - export ORDENV_COMM_PROFILE=eccc/20231121
    - export ORDENV_GROUP_PROFILE=eccc/cmc/1.16.0
    - . /fs/ssm/main/env/ordenv-boot-20231110.sh
    - export EC_ATOMIC_PROFILE_VERSION=1.34.0
    - . $ARMNLIB_SHARE/check_profile_1.1.0
    - . r.load.dot eccc/mrd/rpn/MIG/ENV/rpnpy/2.2.0 eccc/mrd/rpn/code-tools/ENV/cdt-1.6.6/SCIENCE/inteloneapi-2022.1.2
    - . r.load.dot eccc/mrd/rpn/libs/20230906 eccc/cmd/cmda/libs/20230906/inteloneapi-2022.1.2
    - . ssmuse-sh -p /fs/ssm/eccc/cmd/cmds/env/python/py310_2023.07.28_all
    - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmds/apps/ci_fstcomp/1.0.9
    - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmds/cmcdict/202407/00
    - . ssmuse-sh -d /fs/ssm/eccc/cmd/cmds/fstpy/202408/00
  script:
    - cd livraison
    - export SSM_TEST_SPOOKIPY=1
    - DEPLOY_DIR=${deploy_dir_prefix}/${CI_PIPELINE_ID}
    - echo ${DEPLOY_DIR}
    - ./make_ssm_package.py --install --temp ${DEPLOY_DIR}
    - echo $(pwd -P)
    - . ssmuse-sh -x ${DEPLOY_DIR}/spookipy/$( grep __version__ ../spookipy/__init__.py | awk '{print $3}' | tr -d "'" )/all
    - ./test_ssm_package.py
    - cp spookipy_*.ssm ${temp_dir}
  artifacts:
    expire_in: 1 hrs
    paths:
      - livraison/
  only:
    - /^r-\d+\.\d+\.\d+/

deploy:
  stage: deploy
  script:
    - cd ${deploy_dir_prefix}
    - rm -f latest
    - ln -s ${CI_PIPELINE_ID} latest
  only:
    - master

remove_ssm:
  stage: deploy
  script:
    - DEPLOY_DIR=${deploy_dir_prefix}/${CI_PIPELINE_ID}
    - rm -r ${DEPLOY_DIR}
  except:
    - master

keep_ssm_package:
  stage: keep_ssm_package
  script:
    - cd livraison
    - cp *.ssm ${ssm_dir_prefix}/
    - echo "Your packages are here ${ssm_dir_prefix}"
  only:
    - /^r-\d+\.\d+\.\d+/
