[project]
name = "spookipy"
description = "Collection of python algorithms that work with dataframes obtained with fstpy or numpy arrays"
authors = ["Sebastien Fortier <sebastien.fortier@canada.ca>"]
channels = ["fortiers", "conda-forge", "nodefaults"]
platforms = ["linux-64"]

[tasks.test]
description = "Run package tests"
cmd = "cd test && pytest -vrf"

[tasks.lint]
description = "Run lint on package"
cmd = "ruff check spookipy"

[tasks.lint-fix]
description = "Run lint-fix on package"
cmd = "ruff check --fix spookipy"

[tasks.format]
description = "Run format on package"
cmd = "ruff format spookipy"

[tasks.build]
description = "Build package"
cmd = "python -m pip install . -vv --no-deps --no-build-isolation"

[tasks.doc]
description = "Make docs"
cmd = "cd doc && make doc"

[tasks.get-version]
description = "Check version"
cmd = "python -c \"import spookipy; print(spookipy.__version__)\""

[tasks.conda-build]
cmd = "rm -rf /tmp/conda-build && rattler-build build --recipe-dir conda.recipe --output-dir /tmp/conda-build -c fortiers -c conda-forge --channel-priority disabled"

[tasks.render]
cmd = "conda-smithy rerender"

[tasks.conda-upload]
cmd = "rattler-build upload anaconda -v -o fortiers /tmp/conda-build/linux-64/spookipy-*.conda"
depends-on = ["conda-build"]

[dependencies]
python = "==3.10.12"
numpy = "==1.24.4"
numexpr = "==2.7.3"
cf-units = "==3.2.0"
cmcdict = "==2025.3.0"
dask = "==2023.7.1"
pyarrow = "==11.0.0"
fstpy = "==2025.3.0"
pandas = "==1.5.1"
polars = "==0.18.8"

[feature.dev.dependencies]
myst-parser = "==1.0.0"
nbsphinx = "==0.9.2"
pip = "*"
pytest = "==7.4.0"
ruff = ">=0.0.280"
sphinx = "==5.3.0"
sphinx-autodoc-typehints = "==1.21.8"
sphinx-gallery = "==0.13.0"
sphinx_rtd_theme = "==0.5.1"
pygments = "==2.12.0"
ipython = "==8.14.0"
wheel = "*"
ci_fstcomp = ">=2025.1.0"


[environments]
dev = ["dev"]

[target.linux-64.dependencies]
