** Français

*Description:*

- Permet de découper un morceau de grille, défini par son point
supérieur gauche et son point inférieur droit.


*/Notes:/*
Ce plugin permet de créer une grille complètement autonome
S'il est désiré de fusionner plusieurs grilles, ces grilles doivent
avoir été découpées par ce plugin dans la même exécution de Spooki


*Méthode d'itération:*

- Point par point.

*Dépendances:*

- Un ou plusieurs champ(s) sur une ou plusieurs grille(s) source(s)

*Résultat(s):*

- Les champs en entrée sur un morceau de grille, avec les mêmes
métadonnées qu'en entrée.

*Algorithme:*

- Les grilles d'entrée sont référencées, ainsi que leurs données et
leurs descripteurs
- Les grilles de sortie sont créées en copiant les paramètres des
grilles d'entrée et en modifiant les dimensions
- Les données désirées sont copiées.

*Références:*

- N/D

*Mots clés:*

- SYSTÈME/SYSTEM, grille/grid, découpage/cut, sélection/select

*Usage:*

*Exemple d'appel:* 

#+begin_example
...
spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/GridCut/testsFiles/inputFile.std] >>
            [GridCut --startPoint 5,16 --endPoint 73,42] >>
            [WriterStd --output /tmp/$USER/outputFile.std]"
...

#+end_example

*Validation des résultats:*

*Contacts:*

- Auteur(e) : [[https://wiki.cmc.ec.gc.ca/wiki/User:Martinm][Maximilien
Martin]]
- Codé par : [[https://wiki.cmc.ec.gc.ca/wiki/User:Martinm][Maximilien
Martin]] [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortiers][Sébastien
Fortier]]
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
[[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Voir la référence à [[file:GridCut_8cpp.html][GridCut]].

Tests unitaires



*Ce plugin utilise:*\\

*Ce plugin est utilisé par:*\\

** English

*Description:*

Cuts a piece out of a grid, defined by its upper left hand corner and
lower right hand corner.


*/Notes:/*

- This plug-in allows for the creation of a completely autonomous
  grid.
- If one desires to merge several grids, these grids must have been
  cut by this plug-in in the same SPOOKI execution.

*Iteration method:*

- Point by point.

*Dependencies:*

- One or several field(s) on one or several input grid(s).

*Result(s):*

- The input fields on a piece of the grid, with the same input
  metadata.

*Algorithm:*

- The input grids are referenced, as well as their data and their
  descriptors.
- The output grids are created by copying the input grid parameters
  and by modifying the dimensions.
- The desired data is copied.

*Reference:*

- N/A

*Keywords:*

- SYSTÈME/SYSTEM, grille/grid, découpage/cut, sélection/select

*Usage:*

#+begin_example
          [GridCut --help]
          --help                      Produce help message
          --optimizationLevel arg     Level of optimization, by default use global optimization level
          --verbose                   Verbosity level
          --startPoint arg            The upper left point of the matrix
          --endPoint arg              The lower right poinr of the matrix
      
#+end_example

*Call example:* 

#+begin_example
          ...
          spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/GridCut/testsFiles/inputFile.std] >>
          [GridCut --startPoint 5,16 --endPoint 73,42] >>
          [WriterStd --output /tmp/$USER/outputFile.std]"
          ...
      
#+end_example

*Results validation:*

*Contacts:*

- Author : [[https://wiki.cmc.ec.gc.ca/wiki/User:Martinm][Maximilien
  Martin]]
- Coded by : [[https://wiki.cmc.ec.gc.ca/wiki/User:Martinm][Maximilien
  Martin]] [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortiers][Sébastien
  Fortier]]
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Reference to 


Units tests



*Uses:*\\

*Used by:*\\


