[project]
name = "spookipy-tests"
description = "Test environments for spookipy"
authors = ["Sebastien Fortier <sebastien.fortier@ec.gc.ca>"]
channels = ["fortiers", "conda-forge", "nodefaults"]
platforms = ["linux-64"]

[tasks]
tests = "python test_spookipy.py"


[dependencies]

[feature.py38.dependencies]
python = "3.8.*"
spookipy = ">=2025.3.0"

[feature.py39.dependencies]
python = "3.9.*"
spookipy = ">=2025.3.0"

[feature.py310.dependencies]
python = "3.10.*"
spookipy = ">=2025.3.0"

[feature.py311.dependencies]
python = "3.11.*"
spookipy = ">=2025.3.0"

[feature.py312.dependencies]
python = "3.12.*"
spookipy = ">=2025.3.0"

[feature.py313.dependencies]
python = "3.13.*"
spookipy = ">=2025.3.0"

[environments]
py38 = ["py38"]
py39 = ["py39"]
py310 = ["py310"]
py311 = ["py311"]
py312 = ["py312"]
py313 = ["py313"] 
