package:
  name: spookipy
  version: 2024.08.00


build:
  number: 0


requirements:
  build:
    - python
    - pandas >=1.2.4
    - numpy >=1.23.0
    - dask >=2021.8.0
    - xarray
    - fortiers::fstpy >=2024.08.00

  run:
    - python
    - pandas >=1.2.4
    - numpy >=1.23.0
    - dask >=2021.8.0
    - xarray
    - fortiers::fstpy >=2024.08.00


test:
  imports:
    - spookipy

about:
  home: "https://gitlab.science.gc.ca/cmds/spookipy"
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: "Python api for spooki's weather algorithms"

source:
  path: ../

