** English















*Description:*

- Apply a digital filter of Stencil type on a data set.
- The filter, applied on one given point, in one direction of the given
  field, is characterized by a list of weights (odd number) symmetrical
  to the considered point and to the number of times it is applied.
- The filter is applied successively in each direction of the given
  field.

*Iteration method:*

- Point-by-point

*Dependencies:*

- A meteorological field on a grid.

*Result(s):*

- The filtered values of the meteorological field.

*Algorithm:*

#+begin_quote
  For F, a given field of components F(i), in the direction NI (i=1,NI).

  For \(\mbox{ $w_n$}\), (n=1,N), a list of N weights associated to the
  digital filter applied on the F field, which the result \(\mbox{
  $F^*$}\) on each component is expressed as :

  \(\mbox{ $F^*(i) = \frac {\sum_{n=1}^{N} w_n F(i -
  {\scriptstyle[\frac{N+1}{2}- n]})}{\sum_{n=1}^{N} w_n}$}\)    
  \(\mbox{ $, 2 \leq i \leq NI-1$}\)

  This operation is repeated ("repetitions" key), in the direction NI,
  as many times as the specified number in parameter.

  We proceed in the same way in each direction of the F field,
  successively.

  */Note:/* : in the case of a 2D field, the algorithm is first applied
  in the direction NI, and then in the direction NJ.
#+end_quote

*Reference:*

- [[https://wiki.cmc.ec.gc.ca/images/d/dc/Spooki_-_Filtre_html.pdf][Inspired
  from the FILTRE function (stenfilt.f) of the PGSM utility]]

*Keywords:*

- UTILITAIRE/UTILITY, filtre/filter, digital, stencil

*Usage:*

*Call example:* 

#+begin_example
      ...
      spooki_run "[ReaderStd     --input $SPOOKI_DIR/pluginsRelatedStuff/FilterDigital/testsFiles/inputFile.std] >>
                  [FilterDigital --filter 1,2,1 --repetitions 2] >>
                  [WriterStd     --output /tmp/$USER/outputFile.std]"
      ...
#+end_example

*Results validation:*

*Contacts:*

- Author : [[https://wiki.cmc.ec.gc.ca/wiki/User:Yazidih][Hatem Yazidi]]
- Coded by : [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortiers][Sébastien
  Fortier]]
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Reference to 


Units tests



*Uses:*\\

*Used by:*\\



  

