** English















*Description:*

- Merges several grid pieces that were cut in the same SPOOKI execution.

  #+begin_quote
    */Notes:/*
    This plug-in allows for the creation of a completely autonomous
    grid.
  #+end_quote

*Iteration method:*

- Point by point.

*Dependencies:*

- One or several field(s) on several grid pieces.

*Result(s):*

- Input field(s) on the new merged grid.

*Algorithm:*

- The grid pieces are sorted according to their grid of origin. It is
  checked whether they are consecutive and form a rectangular grid from
  which the dimensions are calculated. It is checked whether each grid
  group is consistent and forms a grid with the same dimensions.
- For each group of grid pieces, a grid is created by copying the
  parameters of a piece and by using the previously calculated
  dimensions.
- For each group, we go through every piece in order to copy its data to
  the corresponding location in the output grid. The positioning of the
  data is controlled by a parameter that was set during the cutting of
  the grid.

*Reference:*

- N/A

*Keywords:*

- SYSTÈME/SYSTEM, grille/grid, fusion/merge

*Usage:*

*Call example:* 

#+begin_example
      ...
      spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/GridMerge/testsFiles/inputFile.std] >>
                  ([GridCut --startPoint 0,0 --endPoint 50,51] + [GridCut --startPoint 0,52 --endPoint 50,102]) >>
                  [GridMerge] >>
                  [WriterStd --output /tmp/$USER/outputFile.std]"
      ...
#+end_example

*Results validation:*

*Contacts:*

- Author : [[https://wiki.cmc.ec.gc.ca/wiki/User:Martinm][Maximilien
  Martin]]
- Coded by : [[https://wiki.cmc.ec.gc.ca/wiki/User:Martinm][Maximilien
  Martin]] [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortiers][Sébastien
  Fortier]]
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Reference to 


Units tests



*Uses:*\\

*Used by:*\\



  

