** English















*Description:*

- Calculation of the characteristics of the most-unstable parcel of the
  column, within a user defined depth.

*Iteration method:*

- Column-by-column

*Dependencies:*

- Air temperature in the probed layer, TT
- Geopotential height in the probed layer, GZ and one of the following
  fields in the probed layer:
- Specific humidity, HU
- Relative humidity, HR
- Water vapour mixing ratio, QV
- Dew point temperature, TD
- Dew point depression, ES

*Result(s):*

- Temperature of the most-unstable parcel, MUTT (deg C)
- Dew point of the most-unstable parcel, MUTD (deg C)
-  of the most-unstable parcel,
  MUPX (hPa)
- Relative humidity of the most-unstable parcel, MUHR (fraction)
- Height above the surface of the most-unstable parcel, MUZ (m)
- The maximum wet-bulb potential temperature in the column, TWMX (deg C)

*Algorithm:*

#+begin_example
      Call the Pressure plug-in to obtain PX (hPa) in the probed layer.
      Call the TemperatureWetBulb plug-in to obtain TTW (deg C) in the probed layer.

      Call the InterpolationVertical plug-in with --verticalLevelType MILLIBARS_ABOVE_LEVEL
                                                  --referenceLevel SURFACE
                                                  --verticalLevel (value of --delta)
                                                  --interpolationType LINEAR
                                                  --extrapolationType ABORT
               to find the value of the input fields for the highest level or the probed layer.

      Call the TemperatureWetBulb plug-in to obtain TTW (deg C) for the highest level or the probed layer (with interpolated TT and the chosen humidity field interpolated).

      Initialise TWMX = -999.0
      For each level between the surface and "delta" above the surface:
         Calculate TW (deg C) with the TemperatureWetBulbPotential function.
         If TW > TWMX:
            TWMX = TW
            MUZ (m) = (GZ (dam) - GZsurface (dam)) * 10 (m/dam)
            Replace the values of the following output fields by those at the current level: MUTT, MUPX and the chosen humidity field.

      Call the TemperatureDewPoint and HumidityRelative plug-ins with TT=MUTT, PX=MUPX and the chosen humidity field.

      Call the Zap plug-in to rename HR by MUHR et TD by MUTD.
#+end_example

*Références :*

- Doswell, C. A. and E. N. Rasmussen, 1994: The effect of neglecting the
  virtual temperature correction on CAPE calculations. Wea. Forecasting,
  9, 625-629.

*Keywords:*

- MÉTÉO/WEATHER, température/temperature, parcellesoulevée/liftedparcel,
  plusinstable/mostunstable, convection

*Usage:*

#+begin_quote
  \\
  \\
  *Notes :*\\
  The use of data in pressure coordinates is not allowed as this may
  produce unreliable results.\\
  \\
  Information about the metadata:

  - The verticalLevel (IP1 in RPN STD files) will indicate the base of
    the search for the most unstable layer.\\
  - Characters 2 to 4 of the pdsLabel (5 to 8 of the etiket in RPN STD
    files) will indicate the thickness of the most unstable layer. The
    last character indicates the units (P for hPa above the base of the
    layer and Z for meters above the base of the layer).\\

  *Call example:* 

  #+begin_example
        ...
        spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/ParcelMostUnstable/testsFiles/inputFile.std] >>
                    [ParcelMostUnstable --delta 100mb --iceWaterPhase WATER] >>
                    [WriterStd --output /tmp/$USER/outputFile.std]"
        ...
  #+end_example

  *Results validation:*

  *Contacts:*

  - Author : Neil Taylor
  - Coded by : [[https://wiki.cmc.ec.gc.ca/wiki/User:Stcyrj][Jonathan
    St-Cyr]]
  - Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
    [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

  Reference to 
  

  Unit Tests

  *Uses:*\\

  *Used by:*\\

  

    
  
#+end_quote
