** English















*Description:*

- Calculate precipitation accumulations for given time intervals.
- The various time intervals are defined according to the parameterized
  conditions.

*Iteration method:*

- Point-by-point

*Dependencies:*

- Precipitation accumulation fields required to calculate the requested
  time interval accumulations.
- All precipitation accumulation types found in o.dict may be used:\\
  Ex. PR, FR, PE, RN, SN, A[1-4], AE, AMX, ASG, ASH, ASN, FR[1|2], PB,
  PC, PE[1|2], PE2L, PM, PY, PZ, RN[1|2], SN[1-3], SN10, SND, SNLR, etc

*Result(s):*

- Precipitation accumulation fields (2D) for the requested time
  intervals, in the same units as the dependencies.

*Algorithm:*

- Call plug-in
  [[file:pluginTimeIntervalDifference.html][TimeIntervalDifference]]
  with the values of the four parameter keys.
- The --fieldName key may only be used with the fields listed in the
  Dependencies section.

*Reference:*

- Inspired by operational script "img.pcpn_intvl"

*Keywords:*

- MÉTÉO/WEATHER, précipitations/precipitation, différence/difference,
  type, temps/time, intervalle/interval, accumulation

*Usage:*

#+begin_quote
  \\
  \\
  */Note :/* A single value from each list of the --interval and --step
  conditions applies to a single range defined by --rangeForecastHour.
  The order of the values in the lists of the --interval and --step
  conditions must correspond to the order in the --rangeForecastHour
  list.
#+end_quote

*Call example:* 

#+begin_example
       ...
       spooki_run "[ReaderStd --ignoreExtended --input $SPOOKI_DIR/pluginsRelatedStuff/PrecipitationAmount/testsFiles/inputFile.std] >>
                   [PrecipitationAmount --fieldName SN --rangeForecastHour 0@48 --interval 3 --step 1] >>
                   [WriterStd --output /tmp/$USER/outputFile.std]"
       ...
   
#+end_example

*Results validation:*

*Contacts:*

- Author : [[https://wiki.cmc.ec.gc.ca/wiki/User:Klasam][Marc Klasa]]
- Coded by : [[https://wiki.cmc.ec.gc.ca/wiki/User:Hardyg][Guylaine
  Hardy]]
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Reference to 


Unit tests



*Uses:*\\

*Used by:*\\



  

