** English















*Description:*

- Calculates the potential temperature, which is the temperature of an
  air parcel following adiabatic expansion or compression to a reference
  pressure. On a tephigram such a process can be visualized by raising
  or lowering a parcel along a dry adiabat.\\
  \\
  */Note:/* The reference pressure used here is 1000 hPa.

*Iteration method:*

- Point-by-point

*Dependencies:*

- Air temperature, TT
-  field, PX

*Result(s):*

- Potential temperature, TH (deg K)

*Algorithm:*

#+begin_example
      For TT, the air temperature (deg K) and
      PX the air pressure (hPa)

      Calculate TH as:

      TH = TT*(1000/PX)**(Rd/cpd)

      Where Rd is the gas constant for dry air (Rd = 287.04 J/(kg*K)),
      and cpd is the specific heat of dry air (cpd = 1005.46 J/(kg*K))
#+end_example

*Reference:*

- Markowski, P. and Y. Richardson, 2010: Mesoscale Meteorology in
  Midlatitudes. Wiley-Blackwell, 407 pp.
- Rogers, R. R. and M. K. Yau, 1989: A Short Course in Cloud Physics,
  3rd Ed. Butterworth Heinemann, 290 pp.

*Keywords:*

- MÉTÉO/WEATHER, température/temperature, potentielle/potential

*Usage:*

*Call example:* ==

#+begin_example
      ...
      spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/TemperaturePotential/testsFiles/inputFile.std] >>
                  [TemperaturePotential] >>
                  [WriterStd --output /tmp/$USER/outputFile.std]"
      ...
#+end_example

*Results validation:*

*Contacts:*

- Author : Neil Taylor
- Coded by : Jonathan Cameron,
  [[https://wiki.cmc.ec.gc.ca/wiki/User:Fortinf][François Fortin]]
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Reference to



Units tests



*Uses:*\\

*Used by:*\\



  

