** English















*Description:*

- Calculates wet-bulb potential temperature given temperature and
  dewpoint along with temperature and pressure at the corresponding
  lifting condensation level (LCL).

*Iteration method:*

- Point-by-point

*Dependencies:*

- Air temperature, TT and one of the following fields:
- Dew point temperature, TD
- Water vapour mixing ratio, QV
- Specific humidity, HU
- Relative humidity, HR
- Dew point depression, ES

NOTE : Make sure to provide the dependencies listed above to this
plug-in or to the plug-in results called by this plug-in (see the
section "this plug-in uses"). For more details on this alternative use,
see the
[[/wiki/Spooki/en/Documentation/General_system_description#How_does_it_work.3F][documentation]]
page.

*Result(s):*

- Wet-bulb potential temperature, THW (deg C)

*Algorithm:*

#+begin_example
      Call plug-in Pressure to obtain PX (hPa).
      Call plug-in TemperatureWetBulb to obtain TTW (deg C).

      If PX < 5 hPa:

         TW = -999.0

      Else:

         Call plug-in TemperatureAlongPseudoAdiabat with --endLevel 1000.0hPa and --direction BOTH and keep only the 1000 hPa values to obtain
         TW (deg C).
#+end_example

*Reference:*

- Bluestein, H. B., 1992: Synoptic-Dynamic Meteorology in Midlatitudes
  Volume 1: Principles of Kinematics and Dynamics. Oxford Univeristy
  Press, 431 pp.\\
- Rogers, R. R. and M. K. Yau, 1989: A Short Course in Cloud Physics,
  3rd Ed. Butterworth Heinemann, 290 pp.

*Keywords:*

- MÉTÉO/WEATHER, température/temperature, potentielle/potential,
  thermomètremouillé/wetbulb, humidité/humidity

*Usage:*

*Call example:* 

#+begin_example
      ...
      spooki_run "[ReaderStd --input $SPOOKI_DIR/pluginsRelatedStuff/TemperatureWetBulbPotential/testsFiles/inputFile.std] >>
                  [TemperatureWetBulbPotential] >>
                  [WriterStd --output /tmp/$USER/outputFile.std]"
      ...
#+end_example

*Results validation:*

*Contacts:*

- Author : Neil Taylor
- Coded by : Jonathan Cameron
- Support : [[https://wiki.cmc.ec.gc.ca/wiki/CMDW][CMDW]] /
  [[https://wiki.cmc.ec.gc.ca/wiki/CMDS][CMDS]]

Reference to



Units tests



*Uses:*\\

*Used by:*\\



  

